# ===================================
#  Relation Behavior Config
# ===================================

states:
    label: State
    list: @/plugins/cnesmeteo/user/models/state/columns.yaml
    form: @/plugins/cnesmeteo/user/models/state/fields.yaml
    # toolbar:
    #     buttons: relation_toolbar