# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Location

# Model Form Field configuration
form: @/plugins/cnesmeteo/user/models/country/fields.yaml

# Model Class name
modelClass: CnesMeteo\User\Models\Country

# Default redirect location
defaultRedirect: cnesmeteo/user/locations

# Create page
create:
    title: Create Locations
    redirect: cnesmeteo/user/locations/update/:id
    redirectClose: cnesmeteo/user/locations

# Update page
update:
    title: Edit Locations
    redirect: cnesmeteo/user/locations
    redirectClose: cnesmeteo/user/locations

# Preview page
preview:
    title: Preview Locations